# Generated by Django 4.0.2 on 2022-02-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_title',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_text',
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
