string = input().lower()
water_count = string.count('water')
sand_count = string.count('sand')
fish_count = string.count('fish')
sun_count = string.count('sun')
print(water_count + sand_count + fish_count + sun_count)